using System;
using System.Linq;
using NUnit.Framework;
using RPG.Core;
namespace RPG.Tests
{
    public class CityFoundationsTests
    {
        internal static void End(CrossroadsScenario w){if(w.HandoffPending)Assert.That(w.ContinueHandoff(w.ActiveSide),Is.True);Assert.That(w.EndActivation(w.ActiveSide),Is.True);if(w.HandoffPending)w.ContinueHandoff(w.ActiveSide);}
        internal static void Cycle(CrossroadsScenario w){End(w);End(w);}
        private static CrossroadsScenario World(bool combined=false)=>new CrossroadsScenario(foundations:true,combined:combined);
        private static void Research(CrossroadsScenario w,CityTech tech){Assert.That(w.Foundations.QueueResearch(w,Side.West,tech),Is.True);for(int i=0;i<8&&!w.Foundations.West.Knows(tech);i++)Cycle(w);Assert.That(w.Foundations.West.Knows(tech),Is.True);}
        [Test] public void SeparateMapBaselinesAndProtectedRearCities()
        {var w=World();Assert.That(w.Graph.Nodes.Count,Is.EqualTo(23));Assert.That(w.TargetPressure,Is.EqualTo(24));Assert.That(new CrossroadsScenario().Graph.Nodes.Count,Is.EqualTo(13));Assert.That(w.West.Gold,Is.EqualTo(300));Assert.That(w.Foundations.West.Wood,Is.EqualTo(30));Assert.That(w.PreviewMove(Side.West,13).IsLegal,Is.False);Assert.That(w.West.Formation.Members.Count,Is.EqualTo(6));}
        [Test] public void OutputCreditsOnceAndRegionalDoesNotCountTreasury()
        {var w=World();string before=w.CaptureSave().checksum;Assert.That(w.Foundations.ProjectedRegional(w,Side.West),Is.EqualTo(40));Assert.That(w.CaptureSave().checksum,Is.EqualTo(before));Cycle(w);Assert.That(w.West.Gold,Is.EqualTo(330));Assert.That(w.Foundations.City(Side.West).Regional,Is.EqualTo(40));Assert.That(w.Foundations.West.Wood,Is.EqualTo(36));Assert.That(w.Foundations.West.Iron,Is.EqualTo(24));Assert.That(w.West.KeepFood,Is.EqualTo(36));}
        [Test] public void CapturedSourceKeepsParentAndStockWithoutForeignRegional()
        {var w=World();var f=w.Foundations;f.Capture(16,Side.East);Cycle(w);Assert.That(f.Location(16).Parent,Is.EqualTo(14));Assert.That(f.Location(16).Stock[0],Is.EqualTo(30));Assert.That(w.East.Gold,Is.EqualTo(330));Assert.That(f.City(Side.West).Regional,Is.EqualTo(30));Assert.That(f.City(Side.East).Regional,Is.EqualTo(40));f.Capture(16,Side.West);Cycle(w);Assert.That(w.West.Gold,Is.EqualTo(360));Assert.That(f.City(Side.West).Regional,Is.EqualTo(40));}
        [Test] public void SaturatedSourceStopsOutputWithoutOverflowOrDiscard()
        {var w=World();var f=w.Foundations;f.Capture(16,Side.East);for(int i=0;i<7;i++)Cycle(w);Assert.That(f.Location(16).Stock[0],Is.EqualTo(90));Assert.That(w.West.Gold,Is.EqualTo(300));}
        [Test] public void ConstructionPaysOnceNeedsSubsequentCyclesAndPausesOnActualLoss()
        {
            var w=World();var f=w.Foundations;Assert.That(f.QueueProject(w,Side.West,1,CityProjectKind.DevelopmentII),Is.True);Assert.That(w.West.Gold,Is.EqualTo(200));Cycle(w);Assert.That(f.City(Side.West).Active.Steps,Is.Zero);Cycle(w);Assert.That(f.City(Side.West).Active.Steps,Is.EqualTo(1));
            f.Capture(16,Side.East);f.Capture(17,Side.East);f.Capture(18,Side.East);Cycle(w);Assert.That(f.City(Side.West).Active.Steps,Is.EqualTo(1));Assert.That(f.City(Side.West).Development,Is.EqualTo(1));f.Capture(18,Side.West);Cycle(w);Assert.That(f.City(Side.West).Development,Is.EqualTo(2));f.Capture(18,Side.East);Cycle(w);Assert.That(f.City(Side.West).Development,Is.EqualTo(2));
        }
        [Test] public void StartValidationUsesCurrentProjectionNotOldCycle()
        {var w=World();var f=w.Foundations;f.Capture(16,Side.East);f.Capture(17,Side.East);f.Capture(18,Side.East);Assert.That(f.QueueProject(w,Side.West,1,CityProjectKind.DevelopmentII),Is.True);Assert.That(f.City(Side.West).Active,Is.Null);Assert.That(w.West.Gold,Is.EqualTo(300));}
        [Test] public void ResearchSingleActiveActualProvenanceAndNoDoublePaymentOnRestart()
        {var w=World();var f=w.Foundations;f.QueueResearch(w,Side.West,CityTech.Extraction);f.QueueResearch(w,Side.West,CityTech.Assay);Assert.That(w.West.Gold,Is.EqualTo(260));Cycle(w);Cycle(w);Assert.That(f.West.Research[0].Work,Is.EqualTo(2));f.StopResearch(w,Side.West);Assert.That(f.West.ActiveResearch,Is.EqualTo(CityTech.Assay));f.QueueResearch(w,Side.West,CityTech.Extraction);f.StopResearch(w,Side.West);Assert.That(f.West.ActiveResearch,Is.EqualTo(CityTech.Extraction));Assert.That(w.West.Gold,Is.EqualTo(280));for(int i=0;i<4;i++)Cycle(w);var p=f.West.Research[0];Assert.That(p.Completed,Is.True);Assert.That(p.Provenance.Values.Sum(),Is.EqualTo(6));}
        [Test] public void MinorCaptureRetainsPaidProgressAndDropsOnlyUnpaidQueue()
        {var w=World();Research(w,CityTech.Extraction);var f=w.Foundations;f.QueueProject(w,Side.West,14,CityProjectKind.ExtractionDepot);f.QueueProject(w,Side.West,14,CityProjectKind.AssayOffice);f.Capture(14,Side.East);Assert.That(f.Location(14).Active,Is.Not.Null);Assert.That(f.Location(14).Active.Paused,Is.True);Assert.That(f.Location(14).Queue,Is.Empty);Assert.That(f.Location(14).Parent,Is.EqualTo(1));}
        [Test] public void BoosterStartsFollowingProductionCycleAndCountsActualRate()
        {var w=World();Research(w,CityTech.Extraction);var f=w.Foundations;f.QueueProject(w,Side.West,14,CityProjectKind.ExtractionDepot);Cycle(w);Cycle(w);Assert.That(f.Location(14).Depot,Is.True);Assert.That(f.City(Side.West).Regional,Is.EqualTo(40));Cycle(w);Assert.That(f.City(Side.West).Regional,Is.EqualTo(45));}
        [Test] public void DeepReservationSurvivesPauseAndCancelReleasesOnlyIncrement()
        {var w=World();var f=w.Foundations;f.City(Side.West).Development=3;f.Location(14).Depot=f.Location(14).Assay=true;f.West.Research.Single(p=>p.Tech==CityTech.ResearchMethod).Paid=true;f.West.Research.Single(p=>p.Tech==CityTech.ResearchMethod).Work=12;f.West.Research.Single(p=>p.Tech==CityTech.ResearchMethod).Provenance.Add(1,12);Assert.That(f.QueueProject(w,Side.West,1,CityProjectKind.ResearchInstitute),Is.True);Assert.That(f.City(Side.West).ReservedLoad,Is.EqualTo(2));f.PauseProject(w,Side.West,1);Cycle(w);Assert.That(f.City(Side.West).ReservedLoad,Is.EqualTo(2));f.CancelProject(w,Side.West,1);Assert.That(f.City(Side.West).ReservedLoad,Is.Zero);Assert.That(f.City(Side.West).DeepCapacity,Is.EqualTo(4));}
        [Test] public void ForgeQuoteCompletesOnceOnlySameAliveIdsAndDoesNotHealDirectly()
        {var w=World();var f=w.Foundations;f.City(Side.West).Forge=true;var member=w.West.Formation.Members[1];member.SetBattleResult(new UnitState(new UnitId(1),Side.West,member.Profile,new GridPosition(1,1),Facing.East,17,2));Assert.That(f.OrderRepair(w,Side.West),Is.True);Assert.That(f.West.Repair.Quotes[member.CharacterId],Is.EqualTo(8));Assert.That(w.West.Gold,Is.EqualTo(284));Cycle(w);Assert.That(member.Armor,Is.EqualTo(2));var loaded=w.CaptureSave().Restore();Cycle(w);Cycle(loaded);Assert.That(member.Armor,Is.EqualTo(10));Assert.That(w.CaptureSave().checksum,Is.EqualTo(loaded.CaptureSave().checksum));Cycle(w);Assert.That(member.Armor,Is.EqualTo(10));}
        [Test] public void ForgeDepartureCancelsWithoutRefundAndNoFieldArmorRepair()
        {var w=World();w.Foundations.City(Side.West).Forge=true;var c=w.West.Formation.Commander;c.SetBattleResult(new UnitState(new UnitId(1),Side.West,c.Profile,new GridPosition(1,1),Facing.East,20,0));w.Foundations.OrderRepair(w,Side.West);Assert.That(w.Move(Side.West,2),Is.True);Assert.That(w.Foundations.West.Repair,Is.Null);Assert.That(w.West.Gold,Is.EqualTo(284));Cycle(w);Cycle(w);Assert.That(c.Armor,Is.Zero);}
        [Test] public void SaveRoundTripAllEconomicStateAndContinuesDeterministically()
        {var w=World();w.Foundations.QueueProject(w,Side.West,1,CityProjectKind.DevelopmentII);w.Foundations.QueueResearch(w,Side.West,CityTech.Extraction);Cycle(w);Cycle(w);var d=w.CaptureSave();var loaded=d.Restore();Assert.That(loaded.CaptureSave().checksum,Is.EqualTo(d.checksum));for(int i=0;i<4;i++){Cycle(w);Cycle(loaded);}Assert.That(w.CaptureSave().checksum,Is.EqualTo(loaded.CaptureSave().checksum));}
        [Test] public void CorruptLoadRejectsWithoutChangingLiveWorld()
        {var w=World();var hash=w.CaptureSave().checksum;var d=w.CaptureSave();d.foundations.locations[2].parent=13;d.checksum=d.ComputeHash();Assert.Throws<System.IO.InvalidDataException>(()=>d.Restore());Assert.That(w.CaptureSave().checksum,Is.EqualTo(hash));}
        [Test] public void CombinedRosterAndRealmDirectionArePersistentNotFreeRespec()
        {var w=World(true);Assert.That(w.West.UsedCapacity,Is.EqualTo(27));Assert.That(w.West.Formation.Members.Count,Is.EqualTo(5));Assert.That(w.West.Formation.Members.Last().Profile,Is.EqualTo(UnitProfile.FireMageTII));Assert.That(w.CaptureSave().Restore().West.Formation.Members.Last().PersonalLevel,Is.EqualTo(3));Assert.That(w.RecruitBlocker(Side.West,UnitProfileId.FireMageTI),Is.Not.Null);}
        [Test] public void SourceBudgetsOnlyResetAtGlobalRefreshNotHandoffOrSave()
        {var w=World(true);var mage=w.West.Formation.Members.Last();mage.FireballUsed=2;End(w);Assert.That(mage.FireballUsed,Is.EqualTo(2));var loaded=w.CaptureSave().Restore();Assert.That(loaded.West.Formation.Members.Last().FireballUsed,Is.EqualTo(2));End(w);End(loaded);Assert.That(mage.FireballUsed,Is.Zero);Assert.That(w.CaptureSave().checksum,Is.EqualTo(loaded.CaptureSave().checksum));}
        [Test] public void PaidMageRecruitRequiresVacancyDirectionAndGetsUniqueIdentity()
        {var w=World(true);var f=w.Foundations;f.City(Side.West).MageTower=1;Assert.That(w.Recruit(Side.West,UnitProfileId.FireMageTI),Is.False);var dead=w.West.Formation.Members[1];dead.SetBattleResult(new UnitState(new UnitId(1),Side.West,dead.Profile,new GridPosition(1,1),Facing.East,0,0,UnitStatus.Dead));Assert.That(w.Recruit(Side.West,UnitProfileId.FireMageTI),Is.True);Assert.That(w.West.Gold,Is.EqualTo(150));End(w);var c=w.West.Formation.Members.Last();Assert.That(c.Profile,Is.EqualTo(UnitProfile.FireMageTI));Assert.That(c.PersonalLevel,Is.EqualTo(1));Assert.That(c.CharacterId,Is.Not.EqualTo(dead.CharacterId));Assert.That(w.CaptureSave().Restore().West.Formation.Members.Last().CharacterId,Is.EqualTo(c.CharacterId));}
        [Test] public void TrainingKeepsSameIdAndCurrentPoolsNoImmediateCompletion()
        {var w=World(true);var f=w.Foundations;var dead=w.West.Formation.Members[1];dead.SetBattleResult(new UnitState(new UnitId(1),Side.West,dead.Profile,new GridPosition(1,1),Facing.East,0,0,UnitStatus.Dead));f.City(Side.West).MageTower=2;var tech=f.West.Research.Single(p=>p.Tech==CityTech.ElementalDrills);tech.Paid=true;tech.Work=6;tech.Provenance.Add(1,6);w.Recruit(Side.West,UnitProfileId.FireMageTI);End(w);var c=w.West.Formation.Members.Last();c.AddPersonalXp(20);Assert.That(f.Train(w,Side.West,c.CharacterId,true),Is.True);Cycle(w);Assert.That(c.Profile,Is.EqualTo(UnitProfile.FireMageTI));Cycle(w);Assert.That(c.Profile,Is.EqualTo(UnitProfile.FireMageTII));Assert.That(c.Hp,Is.LessThanOrEqualTo(32));Assert.That(c.CharacterId,Does.EndWith("recruit-1"));Assert.That(w.CaptureSave().Restore().West.Formation.Members.Last().Profile,Is.EqualTo(UnitProfile.FireMageTII));}

        [Test] public void FractionalProductionSurvivesStorageSaveAndRegionalAccounting()
        {var w=World();w.Foundations.Location(16).OutputCondition=.25m;Cycle(w);Assert.That(w.West.Gold,Is.EqualTo(307.5m));Assert.That(w.Foundations.City(Side.West).Regional,Is.EqualTo(32.5m));var loaded=w.CaptureSave().Restore();Cycle(w);Cycle(loaded);Assert.That(w.West.Gold,Is.EqualTo(315));Assert.That(w.CaptureSave().checksum,Is.EqualTo(loaded.CaptureSave().checksum));}
        [Test] public void ResearchLastTickSharesOnlyAcceptedWorkAndContextIsExplicit()
        {var credits=ResearchAccounting.Accept(new System.Collections.Generic.Dictionary<int,decimal>{{1,2},{13,6}},1);Assert.That(credits[1],Is.EqualTo(.25m));Assert.That(credits[13],Is.EqualTo(.75m));Assert.That(credits.Values.Sum(),Is.EqualTo(1));Assert.That(ResearchAccounting.Eligible(true,2,2,true,true,false),Is.False);Assert.That(ResearchAccounting.Eligible(true,1,1,false,false,false),Is.True);}
        [Test] public void DeepAccountingKeepsPhysicalLoadWhenContextIsLost()
        {Assert.That(new[]{1,2,3,4}.Select(DeepAccounting.Capacity),Is.EqualTo(new[]{0,0,4,6}));Assert.That(DeepAccounting.Load(DeepCapability.RecruitmentWing,4),Is.EqualTo(2));Assert.That(DeepAccounting.Increment(1,2),Is.EqualTo(1));Assert.That(DeepAccounting.CanReserve(3,3,1,1),Is.False);Assert.That(DeepAccounting.Load(DeepCapability.Walls,4),Is.Zero);Assert.That(CityFoundations.EstablishmentRequirement(4,1.1m),Is.EqualTo(77));}
        [Test] public void TrainingPausesAwayAndDeathCancelsRatherThanReplacingIdentity()
        {var w=World(true);var f=w.Foundations;var c=new PersistentCharacter("duel-West-recruit-1",UnitProfile.FireMageTI,personalXp:20);var old=w.West.Formation.Members.ToList();old[1].SetBattleResult(new UnitState(new UnitId(1),Side.West,old[1].Profile,new GridPosition(1,1),Facing.East,0,0,UnitStatus.Dead));w.West.Formation.AddRecruit(c);w.West.NextRecruit=2;f.City(Side.West).MageTower=2;var t=f.West.Research.Single(p=>p.Tech==CityTech.ElementalDrills);t.Paid=true;t.Work=6;t.Provenance.Add(1,6);f.Train(w,Side.West,c.CharacterId,true);w.Move(Side.West,2);Cycle(w);Cycle(w);Assert.That(c.Profile,Is.EqualTo(UnitProfile.FireMageTI));Assert.That(f.West.Training,Is.Not.Null);c.SetBattleResult(new UnitState(new UnitId(1),Side.West,c.Profile,new GridPosition(1,1),Facing.East,0,0,UnitStatus.Dead));Cycle(w);Assert.That(f.West.Training,Is.Null);Assert.That(c.Status,Is.EqualTo(PersistentCharacterStatus.Dead));}
    }
}
