using System.Linq;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;
namespace RPG.VisualTrial.Tests
{
 public class HwTrialTests
 {
  const string R="Assets/_Project/VisualTrials/HW_TI";
  [Test]public void CanonicalPrefabHasHealthyHumanoidAndLodsOnOneSkeleton(){var p=AssetDatabase.LoadAssetAtPath<GameObject>(R+"/Generated/HW_TI.prefab");Assert.That(p,Is.Not.Null);var a=p.GetComponent<Animator>();Assert.That(a.avatar.isValid&&a.avatar.isHuman,Is.True);Assert.That(a.runtimeAnimatorController,Is.Not.Null);Assert.That(p.GetComponentsInChildren<SkinnedMeshRenderer>().Length,Is.EqualTo(1));var v=p.GetComponent<HwMeshVariants>();var expected=new[]{102053,75000,50000,50000,25000};for(int i=0;i<expected.Length;i++)Assert.That(v.Candidates[i].Mesh.triangles.Length/3,Is.EqualTo(expected[i]).Within(2));Assert.That(v.Candidates.Select(c=>c.Root).Distinct().Count(),Is.EqualTo(1));Assert.That(v.Candidates.All(c=>c.Mesh.blendShapeCount==0),Is.True,"Grip is baked before all LODs");Assert.That(p.GetComponentsInChildren<Transform>().SelectMany(t=>t.GetComponents<Component>()).Any(c=>c==null),Is.False);}
  [TestCase(HumanBodyBones.RightHand,"RightHandWeaponSocket","GripPoint")]
  [TestCase(HumanBodyBones.LeftLowerArm,"LeftForearmShieldSocket","ShieldMountPoint")]
  public void HumanoidSocketAndPropMarkerCoincide(HumanBodyBones bone,string socketName,string markerName){var go=Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(R+"/Generated/HW_TI.prefab"));try{var a=go.GetComponent<Animator>();var socket=go.GetComponentsInChildren<Transform>().Single(t=>t.name==socketName);var marker=go.GetComponentsInChildren<Transform>().Single(t=>t.name==markerName);Assert.That(a.GetBoneTransform(bone),Is.Not.Null);Assert.That(socket.parent,Is.EqualTo(a.GetBoneTransform(bone)));Assert.That(Vector3.Distance(socket.position,marker.position),Is.LessThan(.00001f));Assert.That(Quaternion.Angle(socket.rotation,marker.rotation),Is.LessThan(.01f));Assert.That(socket.lossyScale.x,Is.EqualTo(1).Within(.001f));Assert.That(socket.lossyScale.y,Is.EqualTo(1).Within(.001f));}finally{Object.DestroyImmediate(go);}}
  [Test]public void CandidateSwapKeepsOneRendererAndCanonicalSkeleton(){var go=Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(R+"/Generated/HW_TI.prefab"));try{var v=go.GetComponent<HwMeshVariants>();var avatar=go.GetComponent<Animator>().avatar;for(int i=0;i<v.Candidates.Length;i++){v.Select(i);Assert.That(v.Body.sharedMesh,Is.SameAs(v.Candidates[i].Mesh));Assert.That(v.Body.bones.Length,Is.EqualTo(v.Body.sharedMesh.bindposes.Length));Assert.That(v.Body.bones.All(b=>b!=null&&b.IsChildOf(go.transform)),Is.True);Assert.That(go.GetComponentsInChildren<SkinnedMeshRenderer>().Length,Is.EqualTo(1));Assert.That(go.GetComponent<Animator>().avatar,Is.SameAs(avatar));Assert.That(v.Body.sharedMaterial,Is.Not.Null);}}finally{Object.DestroyImmediate(go);}}
  [TestCase("Idle")][TestCase("Walk")][TestCase("Attack")][TestCase("Hit")][TestCase("Death")]
  public void ClipsAreHumanoidAndSkeletonOnly(string name){var path=R+"/Animations/"+name+".fbx";var clip=AssetDatabase.LoadAllAssetsAtPath(path).OfType<AnimationClip>().First(c=>c.name==name);Assert.That(clip.humanMotion,Is.True);Assert.That(clip.length,Is.GreaterThan(.5f));Assert.That(AssetDatabase.LoadAssetAtPath<GameObject>(path).GetComponentsInChildren<SkinnedMeshRenderer>(),Is.Empty);var m=(ModelImporter)AssetImporter.GetAtPath(path);Assert.That(m.avatarSetup,Is.EqualTo(ModelImporterAvatarSetup.CopyFromOther));Assert.That(m.sourceAvatar,Is.Not.Null);}
  [Test]public void RestoredPbrHasRealMapsAndCorrectColorSpaces(){var m=AssetDatabase.LoadAssetAtPath<Material>(R+"/Generated/CorrectedPBR.mat");foreach(var slot in new[]{"_BaseMap","_BumpMap","_MetallicGlossMap"})Assert.That(m.GetTexture(slot),Is.Not.Null);Assert.That(m.IsKeywordEnabled("_NORMALMAP"),Is.True);Assert.That(m.IsKeywordEnabled("_METALLICSPECGLOSSMAP"),Is.True);Assert.That(((TextureImporter)AssetImporter.GetAtPath(R+"/Textures/MetallicSmoothness.png")).sRGBTexture,Is.False);Assert.That(((TextureImporter)AssetImporter.GetAtPath(R+"/Textures/Normal.png")).textureType,Is.EqualTo(TextureImporterType.NormalMap));}
  [Test]public void ControllerHasRequiredClipsAndSceneExists(){var p=AssetDatabase.LoadAssetAtPath<GameObject>(R+"/Generated/HW_TI.prefab");Assert.That(p.GetComponent<Animator>().runtimeAnimatorController.animationClips.Select(c=>c.name).Distinct().OrderBy(n=>n),Is.EqualTo(new[]{"Attack","Death","Hit","Idle","Walk"}));Assert.That(AssetDatabase.LoadAssetAtPath<SceneAsset>(R+"/Generated/HW_TI_VisualLab.unity"),Is.Not.Null);}
 }
}
